# Publishing packages to npm and GitHub Packages
# https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages#publishing-packages-to-npm-and-github-packages
name: publish
on:
  release:
    types: [created]
  workflow_dispatch:
    branches:
      - alpha
      - beta
      - master
      - sandbox
jobs:


# npm publish - start
  build:
    strategy:
      matrix:
        architecture:
          # - arm64
          - x64
          # - x86
        node_version:
          # - 12
          - 14
          # - 16
        os:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
    name: job1 . node . v${{ matrix.node_version }} . ${{ matrix.architecture }} . ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      # Setup .npmrc file to publish to npm
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      # Publish to npm
      - run: npm publish --access public || true
      - run: ls -la || true; cat .npmrc || true; cat ~/.npmrc || true; cat package.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          # scope: '@octocat'
      - run: npm install
      # Publish to GitHub Packages
      - run: npm publish || true
      - run: ls -la || true; cat .npmrc || true; cat ~/.npmrc || true; cat package.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# npm publish - end
