# derived from
# https://github.com/actions/starter-workflows/blob/main/ci/node.js.yml
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: CI
on:
  - pull_request
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        architecture:
          # - arm64
          - x64
          # - x86
        node_version:
          - 12
          - 14
          - 16
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    name: pull_request . node . v${{ matrix.node_version }} . ${{ matrix.architecture }} . ${{ matrix.os }}
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - run: sh ci.sh shCiBase
